require "user.options"
require 'user.impatient'
require "user.keymaps"
require "user.plugins"
require "user.colorschemes"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.bufferline"
--[[ require "user.lsp.null-ls" ]]
require "user.toggleterm"
require "user.nvim-tree"
require "user.lualine"
require "user.whichkey"
require 'user.indentline'
require 'user.autocommands'
require 'user.symbols_outline'
require 'user.nvim-ufo'
require 'user.hop_nvim'
require 'user.neogen'
require 'user.markdown-preview'
require 'user.lsp-setup'
require 'user.illuminate'
require 'user.iswap'
require 'user.dap-ui'
require 'user.dap-python'
